image: Visual Studio 2017

version: 0.1.{build}

environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
  SONAR_TOKEN:
    secure: C0pyF3L1eWo4V0x6wF6iBAwLg4z1quHYYWiuhYpE6JgjvbFO7fxr3O+S0FvTiNYD
  GITHUB_ACCESS_TOKEN:
    secure: QChsTeWw2NFueSl/EprFziE6E6lEIbPfVj3NyAu0xoFJMoEk+ZpTjnwWqQMAXN+a
  CODECOV_TOKEN:
    secure: 9YIi32m7/nAZ8j+mTd2bDR6JjS1g5nC2cUST1u2WvagUFIR41DOqOyhYH52SqA5h

branches:
  only:
    - master

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

configuration: Release
platform: Any CPU

notifications:
- provider: Slack
  auth_token:
    secure: Y3i58yrHTt57qU64K8VsB06JMBZr7+9I44tYOd3oyWKnR+vpDilZKpiblJgwM2jHUQ88DzmBaeYzQIS9cA00oaamvT+zc/XizDsL7QBbisE=
  channel: '#build-opensource'

install:
  - ps: wget "https://raw.githubusercontent.com/rducom/ALM/master/build/ComputeVersion.ps1" -outfile "ComputeVersion.ps1"
  - ps: . .\ComputeVersion.ps1
  - ps: $version = Compute "Lucca.Logs\Lucca.Logs.csproj" $env:APPVEYOR_BUILD_NUMBER $env:APPVEYOR_REPO_TAG $env:APPVEYOR_PULL_REQUEST_NUMBER
  - ps: Update-AppveyorBuild -Version $version.Semver
  - choco install dotnetcore-sdk -y
  - dotnet tool install --global dotnet-sonarscanner
  - nuget install OpenCover -Version 4.7.922
  - nuget install Codecov -Version 1.7.2

before_build:
- dotnet restore
- cmd: >-
    IF "%APPVEYOR_PULL_REQUEST_NUMBER%"=="" (
    dotnet sonarscanner begin /k:"Lucca.Logs" /d:"sonar.analysis.mode=publish" /d:"sonar.host.url=https://sonarcloud.io" /o:luccaintegration-github /d:"sonar.login=%SONAR_TOKEN%"
    ) ELSE (
    dotnet sonarscanner begin /k:"Lucca.Logs" /d:"sonar.host.url=https://sonarcloud.io" /o:luccaintegration-github /d:"sonar.login=%SONAR_TOKEN%" /d:"sonar.github.oauth=%GITHUB_ACCESS_TOKEN%" /d:"sonar.pullrequest.provider=github" /d:"sonar.pullrequest.branch=%APPVEYOR_REPO_BRANCH%" /d:"sonar.pullrequest.key=%APPVEYOR_PULL_REQUEST_NUMBER%" /d:"sonar.pullrequest.github.repository=LuccaSA/Lucca.Logs" /d:"sonar.pullrequest.github.endpoint=https://api.github.com"
    )

build_script:
- dotnet restore
- dotnet build Lucca.Logs.sln -c Debug -v minimal

test_script:
- OpenCover.4.7.922\tools\OpenCover.Console.exe -returntargetcode -oldstyle -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test /p:DebugType=full -c Debug Lucca.Logs.Tests\Lucca.Logs.Tests.csproj" -filter:"+[Lucca.Logs*]* -[*Tests*]*" -excludebyattribute:"*.ExcludeFromCodeCoverage*" -output:coverage-opencover.xml
- OpenCover.4.7.922\tools\OpenCover.Console.exe -returntargetcode -oldstyle -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test /p:DebugType=full -c Debug Lucca.Logs.Netcore3.Tests\Lucca.Logs.Netcore3.Tests.csproj" -filter:"+[Lucca.Logs*]* -[*Tests*]*" -excludebyattribute:"*.ExcludeFromCodeCoverage*" -output:coverage-opencover.xml -mergeoutput
- dotnet sonarscanner end /d:"sonar.login=%SONAR_TOKEN%"
- Codecov.1.7.2\tools\codecov -v -f coverage-opencover.xml

after_test:
- ps: dotnet pack Lucca.Logs.Shared\Lucca.Logs.Shared.csproj --configuration $env:CONFIGURATION /p:PackageVersion=$env:APPVEYOR_BUILD_VERSION /p:SourceLinkEnabled=true /p:$("VersionPrefix="+$version.Prefix+";VersionSuffix="+$version.Suffix) -o ..\artifacts
- ps: dotnet pack Lucca.Logs.AspnetCore\Lucca.Logs.AspnetCore.csproj --configuration $env:CONFIGURATION /p:PackageVersion=$env:APPVEYOR_BUILD_VERSION /p:SourceLinkEnabled=true /p:$("VersionPrefix="+$version.Prefix+";VersionSuffix="+$version.Suffix) -o ..\artifacts
- ps: dotnet pack Lucca.Logs.AspnetLegacy\Lucca.Logs.AspnetLegacy.csproj --configuration $env:CONFIGURATION /p:PackageVersion=$env:APPVEYOR_BUILD_VERSION /p:SourceLinkEnabled=true /p:$("VersionPrefix="+$version.Prefix+";VersionSuffix="+$version.Suffix) -o ..\artifacts

artifacts:
  - path: C:\projects\artifacts\*.nupkg
    name: lib

deploy:

- provider: NuGet
  api_key:
    secure: 8iIHDpACXa5QibvCePstSCuzCzxypMpCUwCTQJHFj5ILyXeC687Oy2bDMEJkJmJg
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master
    deploy_public: true
     
- provider: NuGet
  server: https://ci.appveyor.com/nuget/luccaintegration-uvk5yq2c460b
  api_key:
    secure: shmMXUHQLw1te1msoPnFzFFxFEo2lLWF4wriUUAwOaY=
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    deploy_unstable: true
